"""_summary_ Generates a sine lookup table and writes it to a header file."""

import os

import numpy as np

if __name__ == "__main__":
    # Parameters
    TABLE_SIZE = 1024

    t = np.arange(0, TABLE_SIZE) / TABLE_SIZE
    sine_table = np.sin(2 * np.pi * t)
    sine_table = np.append(sine_table, [0])

    output_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "sine_table.h"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n\n")

        f.write("// This file is auto-generated by gen_sine_table.py\n\n")

        f.write("namespace sfFDN {\n\n")

        f.write(f"constexpr uint32_t kSineTableSize = {TABLE_SIZE};\n\n")

        f.write(f"constexpr std::array<float, {TABLE_SIZE+1}> kSineTable = {{\n")
        for value in sine_table:
            f.write(f"    {value:.18e},\n")
        f.write("};\n")

        f.write("} // namespace sfFDN\n")
