include_guard(GLOBAL)

if(APPLE)
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER "/opt/homebrew/opt/llvm@22/bin/clang++")
    endif()
    if(NOT DEFINED CMAKE_C_COMPILER)
        set(CMAKE_C_COMPILER "/opt/homebrew/opt/llvm@22/bin/clang")
    endif()
else()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER "clang++")
    endif()
    if(NOT DEFINED CMAKE_C_COMPILER)
        set(CMAKE_C_COMPILER "clang")
    endif()
endif()
